<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rsl</string>
	</array>
	<key>name</key>
	<string>RSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(Bool|Char|Int|Nat|Real|Text|Unit|abs|all|always|any|as|axiom|card|case|channel|chaos|class|devt_relation|dom|elems|else|elif|end|exists|extend|false|for|hd|hide|if|in|is|inds|initialise|int|inter|isin|len|let|local|ltl_assertion|object|of|out|post|pre|read|real|rng|scheme|skip|stop|swap|then|thoery|test_case|tl|transition_system|true|type|union|until|use|value|variable|while|with|write|~isin|-inflist|-infset|-list|-set)\b</string>
			<key>name</key>
			<string>keyword.control.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>--.*?\n</string>
			<key>name</key>
			<string>comment.line.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;:.*?:&gt;</string>
			<key>name</key>
			<string>comment.line.rsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{!</string>
			<key>end</key>
			<string>!\}</string>
			<key>name</key>
			<string>comment.block.rsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[ \t]*([\w]+)[ \t]*:[^:]</string>
			<key>name</key>
			<string>entity.name.function.rsl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.raw.rsl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.rsl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.rsl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.rsl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^[ \t]*)([\w]+)([ \t]*\([\w\s, ]*\)[ \t]*)(is|as)\b</string>
			<key>name</key>
			<string>keyword.source.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z]\w*\b</string>
			<key>name</key>
			<string>storage.type.source.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(true|false)\b</string>
			<key>name</key>
			<string>constant.language.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>".*"</string>
			<key>name</key>
			<string>string.quoted.double.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'.'</string>
			<key>name</key>
			<string>constant.character.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&gt;&lt;|-&gt;|-m-&gt;|/\\|&lt;=|&lt;&lt;=|&lt;\.|\|\||\|\^\||-~-&gt;|-~m-&gt;|\\/|&gt;=|&gt;&gt;|\.&gt;|\+\+|-\\|&lt;-&gt;|=&gt;|:-|~=|\*\*|&lt;&lt;|&gt;&gt;=|\+&gt;|!!|\|=\||#)</string>
			<key>name</key>
			<string>keyword.operator.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9][0-9]*\.[0-9]+([eE][0-9]+)?[fd]?</string>
			<key>name</key>
			<string>constant.numeric.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>0x[0-9a-f]+</string>
			<key>name</key>
			<string>constant.numeric.rsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.rsl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.rsl</string>
	<key>uuid</key>
	<string>e6a290d8-8de8-4e49-a24b-60ce1481f816</string>
</dict>
</plist>
